name: version-check
on:
  workflow_dispatch
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch latest version
      id: lastversion
      uses: dvershinin/lastversion-action@main
      with:
        repository: 'nginx'
        branch: 'mainline'
    - name: Print latest version
      run: echo "::notice title=NGINX::Latest version is ${{ steps.lastversion.outputs.last_version }}"